name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  deploy-production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: checks
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup pnpm
        uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa # v4
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Install Vercel CLI
        run: pnpm dlx vercel@53.0.1 --version

      - name: Pull Vercel production environment
        run: pnpm dlx vercel@53.0.1 pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_GIT_COMMIT_REF: ${{ github.ref_name }}
          VERCEL_GIT_COMMIT_SHA: ${{ github.sha }}

      - name: Build production deployment
        run: pnpm dlx vercel@53.0.1 build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ENV: production
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_GIT_COMMIT_REF: ${{ github.ref_name }}
          VERCEL_GIT_COMMIT_SHA: ${{ github.sha }}

      - name: Deploy production
        run: pnpm dlx vercel@53.0.1 deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_GIT_COMMIT_REF: ${{ github.ref_name }}
          VERCEL_GIT_COMMIT_SHA: ${{ github.sha }}
